---

- name: create config directory
  ansible.builtin.file:
    name: /etc/automysqlbackup
    state: directory
    mode: 0750

- name: create backup directory
  ansible.builtin.file:
    name: '{{ automysqlbackup_backup_directory }}'
    state: directory
    mode: 0755

- name: copy distributed config
  ansible.builtin.copy:
    src: "{{ automysqlbackup_download_directory }}/automysqlbackup.conf"
    dest: /etc/automysqlbackup/automysqlbackup.conf-DIST
    remote_src: true
    mode: 0640
  when:
    - automysqlbackup_download

- name: create config
  ansible.builtin.template:
    src: automysqlbackup.conf.j2
    dest: /etc/automysqlbackup/automysqlbackup.conf
    mode: 0640

- name: remove pre running script
  ansible.builtin.file:
    name: "{{ automysqlbackup_pre_script.file }}"
    state: absent
  when:
    - automysqlbackup_pre_script.content is defined
    - automysqlbackup_pre_script.content | length == 0
    - automysqlbackup_pre_script.file is defined
    - automysqlbackup_pre_script.file | length != 0

- name: remove post running script
  ansible.builtin.file:
    name: "{{ automysqlbackup_post_script.file }}"
    state: absent
  when:
    - automysqlbackup_post_script.content is defined
    - automysqlbackup_post_script.content | length == 0
    - automysqlbackup_post_script.file is defined
    - automysqlbackup_post_script.file | length != 0

- name: create pre running script
  ansible.builtin.copy:
    dest: "{{ automysqlbackup_pre_script.file }}"
    content: "{{ automysqlbackup_pre_script.content }}"
    mode: 0755
  when:
    - automysqlbackup_pre_script.content is defined
    - automysqlbackup_pre_script.content | length != 0
    - automysqlbackup_pre_script.file is defined
    - automysqlbackup_pre_script.file | length != 0

- name: create post running script
  ansible.builtin.copy:
    dest: "{{ automysqlbackup_post_script.file }}"
    content: "{{ automysqlbackup_post_script.content }}"
    mode: 0755
  when:
    - automysqlbackup_post_script.content is defined
    - automysqlbackup_post_script.content | length != 0
    - automysqlbackup_post_script.file is defined
    - automysqlbackup_post_script.file | length != 0
