---

- name: remove background cron job
  when:
    - not automysqlbackup_cron.enabled | default('false') | bool
    - automysqlbackup_cron.type | default('cron') | string | lower in ["cron", "systemd"]
  block:
    - name: remove cron jobs
      when:
        - not automysqlbackup_cron.type | default('cron') | string == "cron"
      block:
        - name: remove cron job for background jobs
          ansible.builtin.cron:
            name: automatic mysql backup
            job: /usr/local/bin/automysqlbackup
            user: root
            cron_file: mysql_backup
            state: absent
          failed_when: false

        - name: disable systemd timer
          ansible.builtin.service:
            name: mysqlbackup-cron.timer
            enabled: false
            state: stopped
          failed_when: false

- name: create background cron job
  when:
    - automysqlbackup_cron.enabled | default('false') | bool
    - automysqlbackup_cron.type | default('cron') |  string | lower in ["cron", "systemd"]
  block:
    - name: remove cron file
      when:
        - not automysqlbackup_cron.type | default('cron') | string == "cron"
      block:
        - name: remove cron job for background jobs
          ansible.builtin.cron:
            name: automatic mysql backup
            job: /usr/local/bin/automysqlbackup
            user: root
            cron_file: mysql_backup
            state: absent
          failed_when: false

    - name: remove system unit file
      when:
        - not automysqlbackup_cron.type | default('cron') | string == "systemd"
      block:
        - name: disable automysqlbackup background timer
          ansible.builtin.service:
            name: mysqlbackup-cron.timer
            enabled: false
            state: stopped
          failed_when: false

    - name: cron daemon
      when:
        - automysqlbackup_cron.enabled | default('false') | bool
        - automysqlbackup_cron.daemon | default('') | string | length > 0
        - automysqlbackup_cron.type | default('cron') | string == "cron"
      block:
        - name: ensure cron daemon is installed
          ansible.builtin.package:
            name: "{{ automysqlbackup_cron.daemon }}"
            state: present

        - name: create cron job for background jobs
          ansible.builtin.cron:
            name: automatic mysql backup
            job: /usr/local/bin/automysqlbackup
            minute: "{{ automysqlbackup_cron.minute | default('58') }}"
            hour: "{{ automysqlbackup_cron.hour | default('2') }}"
            weekday: "{{ automysqlbackup_cron.weekday | default('*') }}"
            user: root
            cron_file: mysql_backup
            state: present

    - name: systemd unit
      when:
        - automysqlbackup_cron.enabled | default('false') | bool
        - automysqlbackup_cron.type | default('cron') | string == "systemd"
      block:
        - name: create systemd unit file
          ansible.builtin.template:
            src: etc/init/systemd/mysqlbackup-cron.service.j2
            dest: "{{ systemd_lib_directory }}/mysqlbackup-cron.service"
            mode: "0644"
          notify:
            - daemon reload

        - name: create systemd timer file
          ansible.builtin.template:
            src: etc/init/systemd/mysqlbackup-cron.timer.j2
            dest: "{{ systemd_lib_directory }}/mysqlbackup-cron.timer"
            mode: "0644"
          notify:
            - daemon reload

        - name: enable automysqlbackup background timer
          ansible.builtin.service:
            name: mysqlbackup-cron.timer
            enabled: true
            state: started

...
