---

- name: install database client package
  when:
    - automysqlbackup_client_package | default('') | string | length > 0
    - automysqlbackup_client_package | regex_search(".*-client")
  ansible.builtin.package:
    name:
      - "{{ automysqlbackup_client_package }}"
    state: present

- name: find automysqlbackup binary
  ansible.builtin.find:
    paths: /tmp/automysqlbackup
    file_type: file
    patterns:
      - "automysqlbackup"
    recurse: true
  register: found_binary

- name: define automysqlbackup_source
  ansible.builtin.set_fact:
    automysqlbackup_source: "{{
        found_binary.files |
        sort(attribute='path', reverse=True) |
        map(attribute='path') | list | first }}"
  when:
    - found_binary.files is defined
    - found_binary.files | count > 0

- name: copy automysqlbackup
  ansible.builtin.copy:
    src: "{{ automysqlbackup_source }}"
    dest: /usr/local/bin/
    mode: "0755"
    backup: true
    remote_src: true

- name: detect the installed binary
  ansible.builtin.stat:
    path: /usr/local/bin/automysqlbackup
    # get_checksum: false
  register: stat_automysqlbackup_binary
  ignore_errors: true

- name: define automysqlbackup binary checksum
  ansible.builtin.set_fact:
    automysqlbackup_checksum: "{{ stat_automysqlbackup_binary.stat.checksum }}"
  when:
    - stat_automysqlbackup_binary is defined
    - stat_automysqlbackup_binary.stat is defined
    - stat_automysqlbackup_binary.stat.checksum is defined

- name: create local facts
  ansible.builtin.template:
    src: ansible_facts.j2
    dest: /etc/ansible/facts.d/automysqlbackup.fact
    mode: "0755"
