---

- name: prepare
  ansible.builtin.include_tasks: prepare.yml

- name: download
  ansible.builtin.include_tasks: download.yml
  when:
    - automysqlbackup_download

- name: install
  ansible.builtin.include_tasks: install.yml
  when:
    - automysqlbackup_download

- name: configure
  ansible.builtin.include_tasks: configure.yml
