---

- name: download automysqlback to ansible-host
  block:
    - name: create local temp directory
      become: false
      delegate_to: localhost
      file:
        path: "{{ local_tmp_directory }}/automysqlbackup/{{ automysqlbackup_version }}"
        state: directory

    - name: download git sources to local directory {{ local_tmp_directory }}/automysqlbackup/{{ automysqlbackup_version }}
      become: false
      delegate_to: localhost
      git:
        repo: "{{ automysqlbackup_git_repository }}"
        version: "{{ automysqlbackup_git_version | default('master') }}"
        dest: "{{ local_tmp_directory }}/automysqlbackup/{{ automysqlbackup_version }}"
        depth: 1
        update: true
        force: true

    - name: create transfer archive
      become: false
      delegate_to: localhost
      archive:
        path: "{{ local_tmp_directory }}/automysqlbackup/{{ automysqlbackup_version }}"
        dest: "{{ local_tmp_directory }}/automysqlbackup_{{ automysqlbackup_version }}.tgz"

    - name: propagate automysqlbackup.tgz
      become: true
      copy:
        src: "{{ local_tmp_directory }}/automysqlbackup_{{ automysqlbackup_version }}.tgz"
        dest: /tmp

    - name: create temp directory
      file:
        path: /tmp/automysqlbackup
        state: directory

    - name: extract automysqlbackup.tgz
      unarchive:
        src: "/tmp/automysqlbackup_{{ automysqlbackup_version }}.tgz"
        dest: /tmp/automysqlbackup
        remote_src: true

- name: create config directory
  file:
    name: /etc/automysqlbackup
    state: directory

- name: create backup directory
  file:
    name: '{{ automysqlbackup_backup_directory }}'
    state: directory

- name: copy distributed config
  copy:
    src: /tmp/automysqlbackup/{{ automysqlbackup_version }}/automysqlbackup.conf
    dest: /etc/automysqlbackup/automysqlbackup.conf-DIST
    remote_src: true

- name: copy automysqlbackup
  copy:
    src: /tmp/automysqlbackup/{{ automysqlbackup_version }}/automysqlbackup
    dest: /usr/local/bin/
    mode: 0755
    backup: true
    remote_src: true

- name: create config
  template:
    src: automysqlbackup.conf.j2
    dest: /etc/automysqlbackup/automysqlbackup.conf

- name: Add cron job
  cron:
    name: automatic mysql backup
    job: /usr/local/bin/automysqlbackup
    minute: '{{ automysqlbackup_cron_minute }}'
    hour: '{{ automysqlbackup_cron_hour }}'
    user: root
    cron_file: mysql_backup
    state: present
  when: automysqlbackup_cron_enable | bool
